# Default Configuration File for Tadukoo Plugin! -Tadukoo
motd: Welcome to our server! You are in the world %w!
###########################################
#                                         #
#                 Commands                #
###########################################