name: Tadukooplugin
main: com.gmail.lucario77777777.tadukooplugin.Main
version: Alpha 0.1.0.9
description: Tadukoo Plugin
commands:
   ping:
      description: Sends "Pong!" back to the sender.
      usage: /<command> [player]
      permission: Tadukooplugin.ping
      permission-message: You don't have <permission>
   tport:
      description: Teleports a player to another player.
      usage: /<command> [player] <player>
      permission: Tadukooplugin.tport
      permission-message: You don't have <permission>
   heal:
      description: Heals a player.
      usage: /<command> [player]
      permission: Tadukooplugin.heal
      permission-message: You don't have <permission>
   kill:
      description: Kills a player.
      usage: /<command> <player>
      permission: Tadukooplugin.kill
      permission-message: You don't have <permission>
   feed:
      description: Restores a player's hunger.
      usage: /<command> [player]
      permission: Tadukooplugin.feed
      permission-message: You don't have <permission>
   starve:
      description: Starves a player.
      usage: /<command> <player>
      permission: Tadukooplugin.starve
      permission-message: You don't have <permission>
   suicide:
      description: Commit suicide.
      usage: /<command>
      permission: Tadukooplugin.suicide
      permission-message: Sorry, you're not allowed to kill yourself.
   gamemode:
      description: Changes a player's gamemode.
      usage: /<command> [player] [gamemode]
      permission: Tadukooplugin.gamemode
      permission-message: You don't have <permission>
   gm:
      description: Changes a player's gamemode.
      usage: /<command> [player] [gamemode]
      permission: Tadukooplugin.gamemode
      permission-message: You don't have <permission>
   gmt:
      description: Changes a player's gamemode.
      usage: /<command> [player] [gamemode]
      permission: Tadukooplugin.gamemode
      permission-message: You don't have <permission>
   adventure:
      description: Sets a player's gamemode to adventure.
      usage: /<command> [player]
      permission: Tadukooplugin.gamemode
      permission-message: You don't have <permission>
   gma:
      description: Sets a player's gamemode to adventure.
      usage: /<command> [player]
      permission: Tadukooplugin.gamemode
      permission-message: You don't have <permission>
   creative:
      description: Sets a player's gamemode to creative.
      usage: /<command> [player]
      permission: Tadukooplugin.gamemode
      permission-message: You don't have <permission>
   gmc:
      description: Sets a player's gamemode to creative.
      usage: /<command> [player]
      permission: Tadukooplugin.gamemode
      permission-message: You don't have <permission>
   survival:
      description: Sets a player's gamemode to survival.
      usage: /<command> [player]
      permission: Tadukooplugin.gamemode
      permission-message: You don't have <permission>
   gms:
      description: Sets a player's gamemode to survival.
      usage: /<command> [player]
      permission: Tadukooplugin.gamemode
      permission-message: You don't have <permission>
   fly:
      description: Sets flight to true or false for a player.
      usage: /<command> [player]
      permission: Tadukooplugin.fly
      permission-message: You don't have <permission>
   killall:
      description: Kills all online players.
      usage: /<command>
      permission: Tadukooplugin.killall
      permission-message: You don't have <permission>
   motd:
      description: Shows the motd (Message of the Day).
      usage: /<command>
      permission: Tadukooplugin.motd
      permission-message: You don't have <permission>
   time:
      description: Sets the time.
      usage: /<command> <day/night>
      permission: Tadukooplugin.time
      permission-message: You don't have <permission>
   timer:
      description: Counts down from 3.
      usage: /<command>
      permission: Tadukooplugin.timer
      permission-message: You don't have <permission>
   day:
      description: Sets the time to day.
      usage: /<command>
      permission: Tadukooplugin.time
      permission-message: You don't have <permission>
   night:
      description: Sets the time to night.
      usage: /<command>
      permission: Tadukooplugin.time
      permission-message: You don't have <permission>
#   setwarp:
#      description: Sets a warp.
#      usage: /<command> <name>
#      permission: Tadukooplugin.setwarp
#      permission-message: You don't have <permission>
   thelp:
      description: Shows the Tadukoo Plugin help.
      usage: /<command>
      permission: Tadukooplugin.thelp
      permission-message: You don't have <permission>
permissions:
   Tadukooplugin.*:
      description: Gives access to all commands
      children:
         Tadukooplugin.ping: true
         Tadukooplugin.tport: true
         Tadukooplugin.heal: true
         Tadukooplugin.kill: true
         Tadukooplugin.feed: true
         Tadukooplugin.starve: true
         Tadukooplugin.suicide: true
         Tadukooplugin.gamemode: true
         Tadukooplugin.fly: true
         Tadukooplugin.killall: true
         Tadukooplugin.motd: true
         Tadukooplugin.time: true
         Tadukooplugin.timer: true
#         Tadukooplugin.setwarp: true
         Tadukooplugin.thelp: true
   Tadukooplugin.ping:
      description: Gives access to /ping
      default: true
   Tadukooplugin.tport:
      description: Gives access to /tport
      default: op
   Tadukooplugin.heal:
      description: Gives access to /heal
      default: op
   Tadukooplugin.kill:
      description: Gives access to /kill
      default: op
   Tadukooplugin.feed:
      description: Gives access to /feed
      default: op
   Tadukooplugin.starve:
      description: Gives access to /starve
      default: op
   Tadukooplugin.suicide:
      description: Gives access to /suicide
      default: true
   Tadukooplugin.gamemode:
      description: Gives access to /gamemode, /gm, and /gmt
      default: op
   Tadukooplugin.fly:
      description: Gives access to /fly
      default: op
   Tadukooplugin.killall:
      description: Gives access to /killall
      default: op
   Tadukooplugin.motd:
      description: Gives access to /motd
      default: true
   Tadukooplugin.time:
      description: Gives access to /time, /day, and /night
      default: op
   Tadukooplugin.timer:
      description: Gives access to /timer
      default: op
#   Tadukooplugin.setwarp:
#      description: Gives access to /setwarp
#      default: op
   Tadukooplugin.thelp:
      description: Gives access to /thelp
      default: true